---
ID: "aba2e656-32fa-463a-8761-27f1b5fab01c"
Parent: "fd72bac3-7ab1-48cd-84b5-4559953b7e0b"
Template: "fd72bac3-7ab1-48cd-84b5-4559953b7e0b"
Path: "/sitecore/templates/Project/skate-park-collection/Headless Tenant/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241204T074043Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arunsharma23@deloitte.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arunsharma23@deloitte.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b5a8d773-aa70-496c-bf58-16ca5e3b534a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arunsharma23@deloitte.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241204T074043Z
