---
ID: "709f52cd-8b75-4f51-8862-97283e2eb09d"
Parent: "1f5d074d-b11b-40a6-8527-7bdfcf035e28"
Template: "fd2059fd-6043-4dfe-8c04-e2437ce87634"
Path: "/sitecore/content/skate-park-collection/skate-park/Presentation/Partial Designs/Product Content"
SharedFields:
- ID: "55faae90-3bba-4f7f-96fe-13c3f40055ff"
  Hint: Signature
  Value: "product-content"
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{1A60D652-FE4C-4077-8268-6DCD349B2743}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{9E5A5367-FA62-4AB7-865A-588F73BEB3DD}"
              p:before="*"
              s:id="{7A1D9A21-B8D7-42F9-9B0B-92ABF8D1974F}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;BackgroundImage&amp;Styles=%7C%7BF11E7061-22A0-425D-9D2D-5F08EE4C8E31%7D&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=1"
              s:ph="headless-main" />
            <r
              uid="{61F1F3A4-62BF-496D-96CE-549E2F154A91}"
              p:after="r[@uid='{9E5A5367-FA62-4AB7-865A-588F73BEB3DD}']"
              s:id="{3836D951-BB14-43AC-9231-649B7F245DC5}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7B86B686E0-F105-46BD-93C3-9A1DCD73958F%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=2"
              s:ph="/headless-main/container-1" />
            <r
              uid="{2ED0146D-B553-4A42-B5F9-5C552D6064F8}"
              p:after="r[@uid='{61F1F3A4-62BF-496D-96CE-549E2F154A91}']"
              s:id="{C5F905F8-FD1F-444E-A9E5-AC6B774FF0DE}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames=%7BE29EC907-C3F7-4BC0-91AA-8B8B8EB876A4%7D&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=3"
              s:ph="/headless-main/container-1" />
            <r
              uid="{F2DC855A-B2FE-450C-827D-B4D4168EC8B7}"
              p:after="*[1=2]"
              s:id="{7A1D9A21-B8D7-42F9-9B0B-92ABF8D1974F}"
              s:par="GridParameters=%7B7465D855-992E-4DC2-9855-A03250DFA74B%7D&amp;FieldNames&amp;BackgroundImage&amp;Styles&amp;RenderingIdentifier&amp;CSSStyles&amp;DynamicPlaceholderId=4"
              s:ph="/headless-main/container-1" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241204T100304Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arunsharma23@deloitte.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arunsharma23@deloitte.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "704d2119-35b2-4d8a-a814-4daaf05cba19"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arunsharma23@deloitte.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241204T100424Z
