---
ID: "0e7a72d6-9a8f-4f3f-812b-674c88410e9b"
Parent: "13f91cff-43ca-4405-87ea-6a67e3ab4c89"
Template: "13f91cff-43ca-4405-87ea-6a67e3ab4c89"
Path: "/sitecore/templates/Project/skate-park-collection/Skate Park Templates/Skateboard/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20241204T085344Z
    - ID: "31f98cc8-e6b8-4199-8c48-71b65db11ccd"
      Hint: Material
      Value: Bamboo 
    - ID: "48cfe6da-0e86-4a3a-befc-5a22c16b341f"
      Hint: Highlights
      Value: Whether you’re a beginner or a pro, this will work well for you.
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\arunsharma23@deloitte.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\arunsharma23@deloitte.com
    - ID: "6b5ee523-f039-4d69-8216-2a3ddb6a3936"
      Hint: Content
      Value: |
        Looking for a skateboard that can keep up with your shredding skills? The $name is here to take your skating to the next level.&nbsp; Whether you're hitting the skatepark or cruising the streets, the $name is the perfect board for you.<br />
        <br />
        Ready to take your skating to the next level? Order your $name today!<br />
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "75f9e1bc-9db6-444c-b0f8-37c222a10762"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\arunsharma23@deloitte.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20241204T090104Z
